server: http://192.168.0.60:11434
#model: dolphin-mistral:7b
model: granite3.3:8b

# Allowed variables for output (contain within %{}):
# LOG_TYPE: Type of log [journalctl, file]
# TIMESTAMP: Current timestamp of generated file
output:
  path: ./output
  file_template: log_%{LOG_TYPE}_%{TIMESTAMP}

# Allowed variables for prompt (contain within %{}):
# LOG_CONTENT: contents of the log parsed based on file definition.
prompt: |
  You are a helpful IT assistant.
  
  First, give a quick overview of any information about the system the log is for, including server name, IP address, etc. to give the user context for the following information.

  WARNING, ERROR, CRITICAL, or FATAL log entries are the entries that should be cause for concern. Based on the below log, can you call out any problematic log entries with their timestamp in PST, and give a brief synopsis of what that log calls out. If there are none that match this, let the user know and give a very high-level overview of the logs.
  
  If we have any concerning log entries, can you summarize these log entries and provide specifically the entries and their line numbers? Give specific recommendations on remediations where possible.

  Finally, conclude with a brief synopsis of the findings and call out if there's anything to be concerned about or not. If the behavior seen in the log is typical, be sure to let the user know using the exact phrase "All systems nominal, with no major problems detected."
  
  Use only plaintext for formatting. Do not use any Markdown whatsoever. Remember to treat the user as a professional with a higher than average understanding of the subject matter.
  
  Here's the log contents:
  %{LOG_CONTENT}